### PR TITLE
Support for Titanium SDK 6.+

### PR DESCRIPTION
**Pull request by chmiiller**
Based on Alan Escobar's (@alan89) commit: https://github.com/alan89/sc.roundedavatar/tree/6.0.0.GAVersion

### CODE REVIEW

**Comment by linqcan** [comment]
I am unable to verify this as I haven't worked with Ti for a long while.
Hopefully @RonaldTreur or @timanrebel can help you out!

**Comment by timanrebel** [comment]
Thanks for submitting! I'll merge it right away

**Comment by timanrebel** [comment]
oh wait, I don't have write access anymore on this branch, so @RonaldTreur has to do it :)

**Comment by RonaldTreur** [comment]
Sorry for the delay!

**Pull request merged**
